name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            alferov_2025.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: alferov_2025.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Auto-release ${{ env.DATE }}"
          files: alferov_2025.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          git checkout --orphan gh-pages
          git rm -rf .

          # Create a README or .nojekyll file so GitHub Pages works well
          echo "Deployed PDFs" > README.md
          touch .nojekyll

          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Deploy PDF to GitHub Pages [skip ci]"
          git push -f origin gh-pages
